L23/DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HW23.urls')),
    path('accounts/', include('users.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

L23/DjangoProject/HW23/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
from django.views.decorators.cache import cache_page

app_name = 'HW23'
urlpatterns = [
    path('', views.index, name='index'),
    path('game/', cache_page(60, cache='caches_files')(views.game_views), name = 'games',),
    path('game/<slug:game_slug>', views.game_detail, name = 'game_views',),
    path('category/', cache_page(60*5, cache='caches_files')(views.category_views), name = 'categories',),
    path('category/<str:category>', cache_page(60*5, cache='caches_files')(views.category_views), name = 'categories',),
    path('game/<slug:game_slug>/comment', views.CommentCreateView.as_view(), name='comment-add'),
    path('comment/<int:pk>/update/', views.CommentUpdateView.as_view(), name='comment-upd',),
    path('comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment-del',),
]

L23/DjangoProject/api/urls.py
from .views import *
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions


schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path('games/', api_games),
    path('games2/', GetGameInfoView.as_view()),
    path('comments/', GetCommentInfoView.as_view()),
    path('category/', api_categories),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

L23/DjangoProject/users/urls.py
from django.urls import path, re_path, include
from . import views
from django.contrib.auth.views import LoginView


app_name = 'users'
urlpatterns = [
                path('register/', views.register, name='register'),
                # path('login/', LoginView.as_view(template_name = 'users/login.html',), name='login'),
                path('login/', views.login_view, name='login'),
                path('logout/', views.logout_view, name='logout'),
                path('change/', views.UserChangePassword.as_view(), name='UserChangePassword'),
                
                ]

L23/DjangoProject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{%block title%} {% endblock %}</title>
    <style>
        #navbar ul{
          display: none;
          background-color: #f90;
          position: absolute;
          top: 100%;
        }
        #navbar li:hover ul { display: block; }
        #navbar, #navbar ul{
          margin: 0;
          padding: 0;
          list-style-type: none;
        }
        #navbar {
          height: 30px;
          background-color: #666;
          padding-left: 25px;
          min-width: 470px;
        }
        #navbar li {
          float: left;
          position: relative;
          height: 100%;
        }
        #navbar li a {
          display: block;
          padding: 6px;
          width: 100px;
          color: #fff;
          text-decoration: none;
          text-align: center;
        }
        #navbar ul li { float: none; }
        #navbar li:hover { background-color: #f90; }
        #navbar ul li:hover { background-color: #666; }
      </style>
    </head>
    <body>
      <input type="hidden" name="next" {% if equest.path != '' %} value="{{ request.GET.next }}" {% else %} value="index/" {% endif %}/>
      <ul id="navbar">
        <li><a href="/">Главная</a></li>
        <li><a href="/category/">Категории</a>
          <ul>
            <li><a href="/category/RPG"> RPG </a></li>
            <li><a href="/category/action"> action </a></li>
          </ul>
        {% if user.is_authenticated %}
          <li>{{ user.get_username }}</li>
          <li><a href="{% url 'users:logout' %}?next={{request.path}}">Выход</a>
        {% else %}
          <li><a href="{% url 'users:register' %}?next={{request.path}}">Регистрация</a>
          <li><a href="{% url 'users:login' %}?next={{request.path}}">Авторизация</a>
        {% endif %}
        </li>
      </ul>
</head>
<body>

<div>
{% block content%}
{% endblock %}
</div>
</body>
</html>

L23/DjangoProject/templates/game.html
{% extends "base.html"%}
{% load static %}
<hr>
{% block content %}
{% block sort %}
<div style="float:right">
    <p class="block-text">sort by:</p>
    <a class="block-link" href="?sort=name">Name</a>
    <a class="block-link" href="?sort=price">Price</a>
</div>
{% endblock %}
<div>
    <p>{{ game.name }}</p>
    <p>Price: {{game.price}} Dollars </p>
    <img src={{game.game_image.url}} alt="{{game.name}}" width="450">
    <p>Category: <a href=/category/{{game.category}}> {{game.category}} </a></p>
    <p>Разработчик: {{game.gameDev}}</p>
    <p>Статус: {{game.status}}</p>
    <p>Дата релиза: {{game.release_date}}</p>
    <p>Дата последнего обновления информации: {{game.upd_date}}</p>
    <p>Описание: {{game.description}}</p>
    <p>Средняя оценка пользователей: {{ game.rating_avg }}</p>
    <hr>
</div>
<div>
{% if last_visited %}
    <p>Вы просматривали страницу {{amount_visited}} раз, последний в: {{last_visited}}</p>
{% endif %}

{% if user.is_authenticated %}
    {% if not comment_user %}
        <a href="{{request.path}}/comment">Добавить комментарий</a>
    {% else %}
        {% for comment in comment_user %}
            <p>Автор: {{ comment.author }}</p>
            <p>Заголовок: {{ comment.title }}</p>
            <p>Комментарий: {{ comment.content }}</p>
            <p>Оценка: {{ comment.rating }}</p>
            <p>Дата создания: {{ comment.create_date }}</p>
            <p>Дата редактирования: {{ comment.upd_date }}</p>
            
            <a href="{% url 'HW23:comment-upd' pk=comment.pk %}">Обновить комментарий</a>
            <a href="{% url 'HW23:comment-del' pk=comment.pk %}">Удалить комментарий</a>
        {% endfor %}
    {% endif %}
{% endif %}
</div>
{% for comment in comments_other %}
    <div>
    <p>Автор: {{ comment.author }}</p>
    <p>Заголовок: {{ comment.title }}</p>
    <p>Комментарий: {{ comment.content }}</p>
    <p>Оценка: {{ comment.rating }}</p>
    <p>Дата создания: {{ comment.create_date }}</p>
    <p>Дата редактирования: {{ comment.upd_date }}</p>
    </div>
{% endfor %}
{% endblock %}

L23/DjangoProject/templates/games.html
{% extends "base.html"%}
{% load static %}
<hr>
{% block content %}
{% block sort %}
<div style="float:right">
    <p class="block-text">sort by:</p>
    <a class="block-link" href="?sort=name">Name</a>
    <a class="block-link" href="?sort=price">Price</a>
</div>
{% endblock %}
<div>
    {% for game in games %}
    <p><a href=/game/{{game.slug}}> {{ game.name }}</a></p>
    <p>Price: {{game.price}} Dollars </p>
    <img src={{game.game_image.url}} alt="{{game.name}}" width="450">
    <p>Category: <a href=/category/{{game.category}}> {{game.category}} </a></p>
    <p>Разработчик: {{game.gameDev}}</p>
    <p>Статус: {{game.status}}</p>
    <p>Дата релиза: {{game.release_date}}</p>
    <p>Дата последнего обновления информации: {{game.upd_date}}</p>
    <p>Описание: {{game.description}}</p>
    <hr>
    {% endfor %}
</div>
{% endblock %}

L23/DjangoProject/templates/index.html
{% extends "base.html"%}
{% load static %}
{%block title%} Главная {% endblock %}
<div>
    <p><a href="categories"> Categories </a></p>
</div>
<hr>
{% block content %}
{% block sort %}
<div style="float:right">
    <p class="block-text">sort by:</p>
    <a class="block-link" href="?sort=name">Name</a>
    <a class="block-link" href="?sort=price">Price</a>
</div>
{% endblock %}
<div>
    {% for game in games %}
    <p><a href="game/{{game.slug}}"> {{game.name}} </a></p>
    <p>Price: {{game.price}} Dollars </p>
    <img src="/media/{{game.game_image}}" alt="{{game.name}}" width="250">
    <p>Category: <a href=/category/{{game.category}}> {{game.category}} </a></p>
    <hr>
    {% endfor %}
</div>

{% endblock %}